//jshint esversion: 6
//general type action types
export const INITIATE_AJAX_CALL = 'INITIATE_AJAX_CALL';
//export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//user specific action types
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
//export const GET_CURRENT_USER = 'GET_CURRENT_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const USER_AUTHORIZATION_SUCCESS = 'USER_AUTHORIZATION_SUCCESS';
export const GET_CURRENTUSER_SUCCESS = 'GET_CURRENTUSER_SUCCESS';

//service specific action types
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';

//services category action types
export const LOAD_SERVICE_CATEGORIES_SUCCESS = 'LOAD_SERVICE_CATEGORIES_SUCCESS';
export const CREATE_SERVICE_CATEGORY_SUCCESS = 'CREATE_SERVICE_CATEGORY_SUCCESS';
export const UPDATE_SERVICE_CATEGORY_SUCCESS = 'UPDATE_SERVICE_CATEGORY_SUCCESS';
export const DELETE_SERVICE_CATEGORY_SUCCESS = 'DELETE_SERVICE_CATEGORY_SUCCESS';