//jshint esversion: 6
//general type action types
export const INITIATE_AJAX_CALL = 'INITIATE_AJAX_CALL';
//export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const SAVE_NAVIGATOR = 'SAVE_NAVIGATOR';

//user specific action types
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
//export const GET_CURRENT_USER = 'GET_CURRENT_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const USER_AUTHORIZATION_SUCCESS = 'USER_AUTHORIZATION_SUCCESS';
export const GET_CURRENTUSER_SUCCESS = 'GET_CURRENTUSER_SUCCESS';

//service specific action types
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';

//services category action types
export const LOAD_SERVICE_CATEGORIES_SUCCESS = 'LOAD_SERVICE_CATEGORIES_SUCCESS';
export const CREATE_SERVICE_CATEGORY_SUCCESS = 'CREATE_SERVICE_CATEGORY_SUCCESS';
export const UPDATE_SERVICE_CATEGORY_SUCCESS = 'UPDATE_SERVICE_CATEGORY_SUCCESS';
export const DELETE_SERVICE_CATEGORY_SUCCESS = 'DELETE_SERVICE_CATEGORY_SUCCESS';

//cart action types
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';

//rate action types
export const GET_RATES = 'GET_RATES';
export const GET_SERVICE_RATES = 'GET_SERVICE_RATES';
export const GET_SERVICE_LOCATION_RATES = 'GET_SERVICE_LOCATION_RATES';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
export const GET_SERVICE_RATES_SUCCESS = 'GET_SERVICE_RATES_SUCCESS';
export const GET_SERVICE_LOCATION_RATES_SUCCESS = 'GET_SERVICE_LOCATION_RATES_SUCCESS';

//customer action types
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
// export const GET_CUSTOMERS_QUERY = 'GET_CUSTOMERS_QUERY';
// export const GET_CUSTOMERS_QUERY_SUCCESS = 'GET_CUSTOMERS_QUERY_SUCCESS';

//customer action types
export const GET_INVOICES = 'GET_INVOICES';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
// export const GET_CUSTOMERS_QUERY = 'GET_CUSTOMERS_QUERY';
// export const GET_CUSTOMERS_QUERY_SUCCESS = 'GET_CUSTOMERS_QUERY_SUCCESS';

